# fly.toml file generated for z2p on 2023-03-11T20:28:17-06:00

app = "z2p"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "ord"
processes = []

[env]
  RUST_LOG = "TRACE"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
